### ISSUE TITLE
Unit name already taken

### ISSUE THREAD

**Issue by mdrost** [OculusVR/Flicks#17]
Please consider name change as `flick` is already defined as a unit of spectral radiance https://en.wikipedia.org/wiki/Flick_(physics)

**Comment by staylor14** [comment]
If the wikipedia article (https://en.wikipedia.org/wiki/Flick_(time)) is correct, then a better portmanteau would be "frick".  Like, where does the "L" come from other than a desire to make "flick"?

**Comment by blackencino** [comment]
Hey folks,

We actually talked about 'frick' for a little while, but chose 'flick' because of its historical usage as a term for a motion picture, and frick didn't sound particularly nice. The collision with the physics unit 'flick' is frustrating, but at this time we're going to stick with our naming. 

Thank you for your input.

Chris
